import { chromium } from "playwright";
const browser = await chromium.launch({ executablePath: process.env.CHROME || undefined });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 1 });
const errors = []; page.on("pageerror", (e) => errors.push(e.message)); page.on("console", (m) => { if (m.type() === "error") errors.push(m.text().slice(0, 160)); });
const shot = (n, opts = {}) => page.screenshot({ path: `.insyd/shots/audit-${n}.png`, ...opts });
await page.goto("http://localhost:4321/", { waitUntil: "networkidle" });
await page.waitForFunction(() => window.__insydStore?.getState().scan.status === "done", null, { timeout: 240000 });
await page.waitForFunction(() => document.querySelectorAll(".sblock.film img").length > 0, null, { timeout: 120000 }).catch(() => {});
await page.waitForTimeout(1500);
const S = (fn) => page.evaluate(fn);
await S(() => { window.__insydPlayer.seekTo(470); window.__insydStore.getState().select({ type: "element", id: "search.card" }); });
await page.waitForTimeout(600); await shot("01-element");
await S(() => { window.__insydStore.getState().select({ type: "sound", id: "music.bed" }); const t = document.querySelector(".tl-tracks"); t.scrollTop = t.scrollHeight; });
await page.waitForTimeout(600); await shot("02-sound");
await S(() => window.__insydStore.getState().select({ type: "scene", id: "figma" })); await page.waitForTimeout(400); await shot("03-scene");
await S(() => window.__insydStore.getState().select({ type: "brand" })); await page.waitForTimeout(400); await shot("04-brand");
await S(() => window.__insydStore.getState().select(null)); await page.waitForTimeout(300); await shot("05-nothing");
await page.click('button[title^="Connect Claude"]'); await page.waitForTimeout(600); await shot("06-connect"); await page.keyboard.press("Escape"); await page.waitForTimeout(200);
await page.click('button:has-text("Export")'); await page.waitForTimeout(400); await shot("07-export"); await page.keyboard.press("Escape"); await page.mouse.click(1400, 500); await page.waitForTimeout(200);
await page.keyboard.press("?"); await page.waitForTimeout(400); await shot("08-shortcuts"); await page.keyboard.press("Escape");
await page.click("text=Open…"); await page.waitForTimeout(600); await shot("09-open"); 
await page.click(".welcome h1 .btn").catch(() => {}); await page.waitForTimeout(300);
// context menu on a clip
await S(() => { window.__insydStore.getState().select({ type: "element", id: "figma.phone" }); });
await page.waitForTimeout(400);
const clip = await page.$('[data-clip-id="figma.phone"]'); const b = await clip.boundingBox();
await page.mouse.click(b.x + b.width / 2, b.y + b.height / 2, { button: "right" }); await page.waitForTimeout(300); await shot("10-ctx"); await page.keyboard.press("Escape");
console.log("errors:", errors.length ? errors : "none");
await browser.close();
